# Generated by Django 5.1.5 on 2025-03-31 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enhance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_file', models.TextField()),
                ('ai_model', models.CharField(max_length=122)),
                ('output_path', models.TextField()),
                ('ai_precision', models.CharField(max_length=122)),
                ('in_resolution', models.IntegerField()),
                ('interpolation', models.CharField(max_length=122)),
                ('img_output', models.CharField(max_length=122)),
                ('vid_output', models.CharField(max_length=122)),
                ('date', models.DateField()),
            ],
        ),
    ]
