# Generated by Django 5.1.5 on 2025-03-31 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_enhance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enhance',
            name='input_file',
        ),
        migrations.RemoveField(
            model_name='enhance',
            name='output_path',
        ),
    ]
