# Generated by Django 5.1.5 on 2025-03-31 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_enhance_input_file_remove_enhance_output_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='enhance',
            name='input_file',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='inp/'),
        ),
    ]
